import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
const browser = await chromium.launch({ channel:'chromium', headless: true });
const page = await browser.newPage({ viewport: { width:1440,height:940 } });
const errors = []; page.on('pageerror', error=>errors.push(error.message));
const dialogGone=()=>page.locator('dialog').waitFor({state:'detached'});
try {
  await page.goto('http://127.0.0.1:5173');
  await page.waitForFunction(()=>!document.querySelector('.open-button')?.disabled);
  assert.equal(await page.getByRole('button',{name:'Open video',exact:true}).count(),1);
  assert.equal(await page.getByRole('slider').count(),0);
  assert.equal(await page.locator('.sidebar,.queue-panel,.filter-row,.playback-bar').count(),0);
  await page.screenshot({path:'/tmp/videe-redesign-empty.png',fullPage:true});
  await page.locator('input[type=file]').first().setInputFiles(resolve('tests/fixtures/sample.mp4'));
  await page.waitForFunction(()=>{const video=document.querySelector('video');return video&&video.readyState>=2&&video.currentTime>0.2;});
  await page.locator('.transport-play').click();
  await page.waitForFunction(()=>document.querySelector('video').paused);
  await page.getByRole('slider',{name:'Playback position',exact:true}).fill('5');
  await page.waitForFunction(()=>Math.abs(document.querySelector('video').currentTime-5)<0.3);
  await page.getByRole('combobox',{name:'Playback speed'}).selectOption('1.5');
  assert.equal(await page.locator('video').evaluate(video=>video.playbackRate),1.5);
  await page.getByRole('button',{name:'Subtitles',exact:true}).click();
  await page.getByRole('button',{name:'Open subtitles'}).waitFor();
  await page.locator('input[type=file]').nth(1).setInputFiles(resolve('tests/fixtures/subtitle.srt'));
  await page.waitForFunction(()=>document.querySelector('video')?.textTracks[0]?.cues?.length===1);
  await page.getByRole('switch',{name:'Show subtitles'}).uncheck();
  assert.equal(await page.locator('video').evaluate(video=>video.textTracks[0].mode),'hidden');
  await page.getByRole('switch',{name:'Show subtitles'}).check();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await dialogGone();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('switch',{name:'Autoplay',exact:true}).uncheck();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await dialogGone();
  await page.getByRole('button',{name:'Full screen'}).click();
  await page.waitForFunction(()=>!!document.fullscreenElement);
  await page.getByRole('slider',{name:'Playback position'}).fill('6');
  await page.getByRole('button',{name:'Full screen'}).click();
  await page.waitForFunction(()=>!document.fullscreenElement);
  await page.screenshot({path:'/tmp/videe-redesign-player.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile player overflow');
  await page.screenshot({path:'/tmp/videe-redesign-mobile-player.png',fullPage:true});
  await page.getByRole('button',{name:'Back to library'}).click();
  assert.equal(await page.locator('video').count(),0);
  await page.locator('summary[aria-label="Options for sample.mp4"]').click();
  await page.getByRole('button',{name:'Add to favorites',exact:true}).click();
  await page.getByRole('button',{name:'Favorites',exact:true}).click();
  assert.equal(await page.locator('.video-card').count(),1);
  await page.getByRole('textbox',{name:'Search videos'}).fill('absent');
  await page.getByText('No videos found').waitFor();
  await page.getByRole('button',{name:'Clear search'}).click();
  await page.setViewportSize({width:1440,height:940});
  await page.screenshot({path:'/tmp/videe-redesign-library.png',fullPage:true});
  await page.reload();
  await page.getByRole('button',{name:'Play sample.mp4'}).click();
  await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
  assert.ok(await page.locator('video').evaluate(video=>video.currentTime>=5.9));
  assert.equal(await page.locator('video').evaluate(video=>video.paused),true);
  assert.equal(await page.locator('video').evaluate(video=>video.playbackRate),1.5);
  await page.getByRole('button',{name:'Back to library'}).click();
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile library overflow');
  await page.screenshot({path:'/tmp/videe-redesign-mobile-library.png',fullPage:true});
  await page.locator('summary[aria-label="Options for sample.mp4"]').click();
  await page.getByRole('button',{name:'Remove from library',exact:true}).click();
  await page.getByRole('button',{name:'Remove',exact:true}).click();
  await dialogGone();
  await page.getByRole('button',{name:'Open video',exact:true}).waitFor();
  await page.reload();
  await page.getByRole('button',{name:'Open video',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: simplified empty/library/player flows, playback, seek, explicit speed selection, subtitles, fullscreen, favorites, search, persisted resume/settings, mobile layout, deletion; no runtime errors.');
} catch(error) { await page.screenshot({path:'/tmp/videe-redesign-failure.png',fullPage:true}); throw error; }
finally { await browser.close(); }
