import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { copyFile, mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const browser = await chromium.launch({ channel: 'chromium', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 940 } });
const root = await mkdtemp(join(tmpdir(), 'videe-folder-ui-'));
try {
  await mkdir(join(root, 'nested'), { recursive: true });
  await copyFile(resolve('tests/fixtures/sample.mp4'), join(root, 'Inside.mp4'));
  await copyFile(resolve('tests/fixtures/sample.mp4'), join(root, 'nested', 'Deep.mp4'));
  await writeFile(join(root, 'note.txt'), 'skip');
  await page.goto('http://127.0.0.1:5173');
  await page.waitForFunction(() => !document.querySelector('.header-open')?.disabled);
  assert.equal(await page.locator('input.folder-input').evaluate(el => el.hasAttribute('webkitdirectory')), true);
  const chooserPromise = page.waitForEvent('filechooser');
  await page.locator('.app-header .header-open').click();
  const chooser = await chooserPromise;
  await chooser.setFiles(root);
  await page.locator('.video-card').first().waitFor();
  assert.equal(await page.locator('.video-card').count(), 1);
  assert.equal(await page.locator('.video-title').innerText(), 'Inside');
  await page.waitForFunction(() => document.querySelectorAll('.video-thumbnail img').length >= 1, null, { timeout: 20000 });
  assert.equal(await page.locator('.video-list').count(), 1);
  assert.equal(await page.locator('.collection-name').innerText(), basename(root));
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: 'nested', exact: true }).click();
  assert.equal(await page.locator('.video-card').count(), 1);
  assert.equal(await page.locator('.video-title').innerText(), 'Deep');
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: 'All collections', exact: true }).click();
  assert.equal(await page.locator('.video-card').count(), 2);
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: basename(root), exact: true }).click();
  await page.getByRole('button', { name: 'Duration', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Duration', exact: true }).getAttribute('aria-sort'), 'descending');
  await page.reload();
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: basename(root), exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Duration', exact: true }).getAttribute('aria-sort'), 'descending');
  await page.getByRole('checkbox', { name: 'Select Inside.mp4', exact: true }).check();
  await page.locator('.library-selection .choice-menu > summary').click();
  await page.locator('.library-selection .choice-options').getByRole('button', { name: 'Remove from folder', exact: true }).click();
  await page.getByText('Empty collection').waitFor();
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: 'nested', exact: true }).click();
  await page.getByRole('button', { name: 'Delete folder', exact: true }).click();
  await page.locator('dialog.modal').getByRole('button', { name: 'Delete folder', exact: true }).click();
  await page.locator('dialog.modal').waitFor({ state: 'detached' });
  await page.locator('.organization summary[aria-label="Collection"]').click();
  await page.locator('.organization .choice-options').getByRole('button', { name: 'All collections', exact: true }).click();
  assert.equal(await page.locator('.video-card').count(), 1);
  assert.equal(await page.locator('.video-title').innerText(), 'Inside');
  await page.locator('.library-selection').getByRole('button', { name: 'Select all', exact: true }).click();
  await page.getByText('1 selected').waitFor();
  await page.locator('.library-selection').getByRole('button', { name: 'Remove from library', exact: true }).click();
  await page.locator('dialog.modal').getByRole('button', { name: 'Remove', exact: true }).click();
  await page.locator('dialog.modal').waitFor({ state: 'detached' });
  await page.getByRole('heading', { name: 'No videos' }).waitFor();
  await page.getByRole('button', { name: 'Open folder', exact: true }).waitFor();
  console.log('PASS: Nested folders import separately, deleting a folder removes its videos, and selected videos can be removed together.');
} catch (error) {
  await page.screenshot({ path: '/tmp/videe-folder-failure.png', fullPage: true });
  throw error;
} finally {
  await browser.close();
  await rm(root, { recursive: true, force: true });
}
