import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const browser = await chromium.launch({channel:'chromium',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:940}});
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
const dialogGone=()=>page.locator('dialog').waitFor({state:'detached'});
try {
  await page.goto('http://127.0.0.1:5173');
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  assert.equal(await page.getByRole('switch',{name:'Animations',exact:true}).isChecked(),true);
  await page.getByRole('switch',{name:'Animations',exact:true}).uncheck();
  assert.equal(await page.locator('html').getAttribute('data-motion'),'off');
  assert.equal(await page.locator('dialog').evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.getByRole('switch',{name:'Animations',exact:true}).check();
  assert.equal(await page.locator('html').getAttribute('data-motion'),'on');
  await page.getByRole('switch',{name:'Autoplay',exact:true}).uncheck();
  await page.getByRole('combobox',{name:'Appearance'}).selectOption('dark');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await dialogGone();
  const buffer=await readFile('tests/fixtures/sample.mp4');
  await page.locator('input[type=file]').first().setInputFiles([{name:'Zulu.mp4',mimeType:'video/mp4',buffer},{name:'Alpha.mp4',mimeType:'video/mp4',buffer}]);
  await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
  await page.getByRole('slider',{name:'Playback position',exact:true}).fill('4');
  await page.getByRole('button',{name:'Back to library'}).click();
  await page.getByRole('button',{name:/Continue watching/}).filter({visible:true}).click();
  assert.equal(await page.locator('.video-card').count(),1);
  await page.getByRole('button',{name:/All videos/}).filter({visible:true}).click();
  await page.getByRole('combobox',{name:'Sort by'}).selectOption('name');
  assert.equal(await page.locator('.video-title').first().innerText(),'Alpha');
  await page.getByRole('button',{name:'List view',exact:true}).click();
  await page.reload();
  await page.locator('.video-list').waitFor();
  assert.equal(await page.getByRole('combobox',{name:'Sort by'}).inputValue(),'name');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.getByRole('button',{name:'Play Alpha.mp4'}).click();
  await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
  await page.getByRole('button',{name:'Next video',exact:true}).click();
  await page.getByRole('heading',{name:'Zulu.mp4',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
  await page.getByRole('button',{name:'Previous video',exact:true}).click();
  await page.getByRole('heading',{name:'Alpha.mp4',exact:true}).waitFor();
  await page.getByRole('button',{name:'Back to library'}).click();
  await page.locator('summary[aria-label="Options for Zulu.mp4"]').click();
  await page.getByRole('button',{name:'Video info',exact:true}).click();
  await page.getByRole('heading',{name:'Video info'}).waitFor();
  assert.match(await page.locator('.info-list').innerText(),/0:04/);
  await page.keyboard.press('Escape');
  await dialogGone();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('switch',{name:'Resume playback',exact:true}).uncheck();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await dialogGone();
  await page.locator('summary[aria-label="Options for Zulu.mp4"]').click();
  await page.getByRole('button',{name:'Resume Zulu.mp4',exact:true}).click();
  await page.waitForFunction(()=>{const v=document.querySelector('video');return v.readyState>=2&&v.currentTime>=3.9&&!v.paused;});
  await page.locator('video').evaluate(v=>v.pause());
  await page.getByRole('button',{name:'Back to library'}).click();
  await page.locator('summary[aria-label="Options for Zulu.mp4"]').click();
  await page.getByRole('button',{name:'Reset watch history'}).click();
  await page.reload();
  await page.getByRole('button',{name:/Continue watching/}).filter({visible:true}).click();
  await page.getByText('All caught up.').waitFor();
  await page.getByRole('button',{name:/All videos/}).filter({visible:true}).click();
  await page.getByRole('button',{name:'Grid view',exact:true}).click();
  await page.screenshot({path:'/tmp/videe-library-dark.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'List view',exact:true}).click();
  await page.screenshot({path:'/tmp/videe-library-mobile-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('combobox',{name:'Appearance'}).selectOption('light');
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await dialogGone();
  await page.setViewportSize({width:1440,height:940});
  await page.getByRole('button',{name:'Grid view',exact:true}).click();
  await page.screenshot({path:'/tmp/videe-library-light.png',fullPage:true});
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.ok(!/[ぁ-んァ-ヶ一-龠]/.test(await page.locator('body').innerText()),'app labels are English');
  assert.deepEqual(errors,[]);
  console.log('PASS: continue filter, name sort, saved list/theme preferences, ordered next/previous playback, media info, persisted history reset, dark/light and mobile layout.');
} finally { await browser.close(); }
