import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chromium',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const cdp=await page.context().newCDPSession(page);await cdp.send('Media.enable');const mediaEvents=[];cdp.on('Media.playerEventsAdded',e=>mediaEvents.push(e));
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const dialogGone=()=>page.locator('dialog').waitFor({state:'detached'});
try {
 await page.goto('http://127.0.0.1:5173');
 assert.equal(await page.locator('.brand img').getAttribute('src'),'./icon.png');
 assert.equal(await page.getByRole('button',{name:'Lock library',exact:true}).count(),0);
 const buffer=await readFile('tests/fixtures/sample.mp4');
 await page.locator('input[type=file]').first().setInputFiles([{name:'First.mp4',mimeType:'video/mp4',buffer},{name:'Second.mp4',mimeType:'video/mp4',buffer}]);
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.locator('video').evaluate(v=>{v.pause();v.currentTime=0;});
 await page.getByRole('button',{name:'Loop',exact:true}).click();
 assert.equal(await page.locator('.seek-bar').getAttribute('data-loop'),'');
 assert.match(await page.locator('.seek-bar').getAttribute('style')||'',/--loop-b:\s*100%/);
 assert.ok((await page.locator('.seek-play').evaluate(el=>getComputedStyle(el).backgroundImage)).includes('rgb(110, 168, 255)'));
 await page.getByRole('slider',{name:'Loop start',exact:true}).fill('2');
 await page.getByRole('slider',{name:'Loop end',exact:true}).fill('2.1');
 await page.getByText('Set a loop at least 0.25 seconds long.').waitFor();
 await page.getByRole('slider',{name:'Loop end',exact:true}).fill('4');
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('video').currentTime>3.3);
 await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>=2&&v.currentTime<2.8&&!v.paused;});
 await page.getByRole('button',{name:'Loop',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('video').currentTime>4.2,null,{timeout:7000});
 await page.getByRole('button',{name:'Back to library'}).click();
 await page.getByRole('button',{name:'Play First.mp4'}).click();
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 assert.equal(await page.locator('.seek-bar').getAttribute('data-loop'),'');
 await page.locator('video').evaluate(v=>{v.pause();v.currentTime=3.6;});
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>=2&&v.currentTime<2.8&&!v.paused;});
 assert.equal(await page.getByRole('button',{name:'Playback tools',exact:true}).count(),0);
 await page.locator('video').evaluate(v=>v.pause());
 await page.getByRole('button',{name:'Next video',exact:true}).click();
 await page.getByRole('heading',{name:'Second.mp4',exact:true}).waitFor();
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.getByRole('button',{name:'Loop',exact:true}).click();
 assert.equal(await page.getByRole('slider',{name:'Loop end',exact:true}).count(),0);
 await page.getByRole('button',{name:'Loop',exact:true}).click();
 await page.locator('video').evaluate(v=>{v.pause();v.currentTime=0;});
 await page.getByRole('button',{name:'Remove segment',exact:true}).click();
 assert.equal(await page.locator('.seek-bar').getAttribute('data-cut'),'');
 await page.getByRole('slider',{name:'Segment start',exact:true}).fill('1');
 await page.getByRole('slider',{name:'Segment end',exact:true}).fill('3');
 await page.getByRole('button',{name:'Delete selected segment',exact:true}).click();
 await page.getByRole('button',{name:'Remove',exact:true}).click();
 await page.getByText('Removing a segment needs the Videe app.').waitFor();
 await dialogGone();
 await page.getByRole('button',{name:'Remove segment',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.getByRole('button',{name:'Playback tools',exact:true}).count(),0);
 assert.ok(await page.locator('.player-controls').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 assert.ok(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await dialogGone();
 await page.getByRole('button',{name:'Back to library'}).click();
 assert.equal(await page.locator('.continue-feature').count(),0);
 assert.equal(await page.locator('.video-thumbnail img').first().evaluate(el=>getComputedStyle(el).objectFit),'contain');
 assert.deepEqual(errors,[]);
 console.log('PASS: original icon, no header lock, loop bar range, invalid range, saved loop, next video, no playback tools, cut range needs app.');
}catch(e){console.log(JSON.stringify(mediaEvents).slice(-8000));console.log(await page.locator('body').innerText());console.log(await page.locator('video').evaluate(v=>({time:v.currentTime,paused:v.paused,ended:v.ended,loop:v.loop})));throw e;}finally{await browser.close();}
