import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chromium',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const dialogGone=()=>page.locator('dialog').waitFor({state:'detached'});
try {
 await page.goto('http://127.0.0.1:5173');
 assert.equal(await page.locator('.brand img').getAttribute('src'),'./icon.png');
 const buffer=await readFile('tests/fixtures/sample.mp4');
 await page.locator('input[type=file]').first().setInputFiles([{name:'First.mp4',mimeType:'video/mp4',buffer},{name:'Second.mp4',mimeType:'video/mp4',buffer}]);
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.locator('video').evaluate(v=>{v.pause();v.currentTime=2;});
 await page.getByRole('button',{name:'Playback tools',exact:true}).click();
 await page.getByRole('button',{name:/Set A/}).click();
 await page.getByRole('button',{name:/Set B/}).click();
 await page.getByText('Set B at least 0.25 seconds after A.').waitFor();
 await page.locator('video').evaluate(v=>{v.currentTime=4;});
 await page.getByRole('button',{name:/Set B/}).click();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await dialogGone();
 await page.locator('video').evaluate(v=>v.play());
 await page.waitForFunction(()=>document.querySelector('video').currentTime>3.3);
 await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>=2&&v.currentTime<2.8&&!v.paused;});
 await page.getByRole('button',{name:'Playback tools',exact:true}).click();
 await page.getByRole('button',{name:'Clear loop',exact:true}).click();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await dialogGone();
 await page.waitForFunction(()=>document.querySelector('video').currentTime>4.2);
 await page.getByRole('button',{name:'Playback tools',exact:true}).click();
 await page.getByRole('button',{name:'Play queue item Second.mp4',exact:true}).click();
 await page.getByRole('heading',{name:'Second.mp4',exact:true}).waitFor();
 await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.getByRole('button',{name:'Playback tools',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:/Set B/}).isDisabled(),true);
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));
 await page.screenshot({path:'/tmp/videe-playback-tools.png'});
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await dialogGone();
 await page.getByRole('button',{name:'Back to library'}).click();
 assert.equal(await page.locator('.continue-feature').count(),0);
 assert.equal(await page.locator('.video-thumbnail img').first().evaluate(el=>getComputedStyle(el).objectFit),'contain');
 assert.deepEqual(errors,[]);
 console.log('PASS: original icon, no spotlight, uncropped thumbnails, actual A-B repeat, invalid range, clear loop, queue navigation, loop reset, mobile tools.');
}finally{await browser.close();}
