import {useEffect,useState,type ReactNode} from 'react';
const KEY='videe-lock';
export const lockEnabled=()=>localStorage.getItem(KEY)!==null;
async function digest(password:string,salt:Uint8Array<ArrayBuffer>){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:600000},key,256))).map(n=>n.toString(16).padStart(2,'0')).join('');}
async function verify(password:string){const data=JSON.parse(localStorage.getItem(KEY)||'null');if(!data||!Array.isArray(data.salt)||data.salt.length!==16||typeof data.hash!=='string')throw Error('Lock settings are damaged. Restore your app data backup.');return await digest(password,new Uint8Array(data.salt))===data.hash;}
export function SecuritySettings(){const [enabled,setEnabled]=useState(lockEnabled);const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [current,setCurrent]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
const change=async(remove=false)=>{setBusy(true);setMessage('');try{if(enabled&&!await verify(current))throw Error('Incorrect current password.');if(remove){localStorage.removeItem(KEY);setEnabled(false);}else{if(password.length<8)throw Error('Use at least 8 characters.');if(password!==confirm)throw Error('Passwords do not match.');const salt=crypto.getRandomValues(new Uint8Array(16));const hash=await digest(password,salt);localStorage.setItem(KEY,JSON.stringify({salt:Array.from(salt),hash}));setEnabled(true);}setPassword('');setConfirm('');setCurrent('');setMessage(remove?'Password removed.':'Password saved.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save password.');}finally{setBusy(false);}};
return <section className="settings-section security-settings"><h3>Password lock</h3>{enabled&&<label>Current password<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label>}<label>New password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="tool-actions"><button className="secondary-button" disabled={busy} onClick={()=>void change()}>Save password</button>{enabled&&<><button className="secondary-button" disabled={busy} onClick={()=>void change(true)}>Remove password</button><button className="secondary-button" disabled={busy} onClick={()=>window.dispatchEvent(new Event('videe-lock'))}>Lock now</button></>}</div><p role="status">{message}</p></section>;
}
export function PasswordGate({children}:{children:ReactNode}){const [locked,setLocked]=useState(lockEnabled);const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [until,setUntil]=useState(0);const [attempts,setAttempts]=useState(0);
useEffect(()=>{const lock=()=>{if(!lockEnabled())return;document.querySelectorAll('video').forEach(v=>{v.pause();if(document.pictureInPictureElement===v)void document.exitPictureInPicture().catch(()=>{});});if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});setPassword('');setLocked(true);};window.addEventListener('videe-lock',lock);const storage=(e:StorageEvent)=>{if(e.key===KEY&&e.newValue)lock();};window.addEventListener('storage',storage);return()=>{window.removeEventListener('videe-lock',lock);window.removeEventListener('storage',storage);};},[]);
if(!locked)return children;
return <main className="lock-screen"><form onSubmit={async e=>{e.preventDefault();if(busy)return;if(Date.now()<until){setError('Wait 30 seconds, then try again.');return;}setBusy(true);try{if(!await verify(password)){const count=attempts+1;setAttempts(count);if(count%5===0)setUntil(Date.now()+30000);throw Error('Incorrect password.');}setPassword('');setError('');setAttempts(0);setLocked(false);}catch(e){setError(e instanceof Error?e.message:'Could not unlock.');}finally{setBusy(false);}}}><img src="./icon.png" width="64" height="64" alt=""/><h1>Library locked</h1><label>Password<input autoFocus type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-button" disabled={busy||!password}>Unlock library</button><p role="alert">{error}</p></form></main>;
}
